os: linux
dist: bionic
language: python

python:
  - "3.6"
  - "3.7"

services:
  - neo4j

addons:
  apt:
    packages:
      - libsnappy-dev

install:
  - pip install python-snappy==0.5.4
  - pip install -r requirements.txt

script:
  - make tests
