"""Add the news table

Revision ID: 48570234e11c
Revises: 956e9a3dd287
Create Date: 2019-06-17 15:16:29.844841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType


# revision identifiers, used by Alembic.
revision = '48570234e11c'
down_revision = '956e9a3dd287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_created_at'), 'news', ['created_at'], unique=False)
    op.create_table('users_news',
    sa.Column('user_id', UUIDType(binary=False), nullable=False),
    sa.Column('news_id', UUIDType(binary=False), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'news_id'),
    sa.UniqueConstraint('user_id', 'news_id', name='users_news_uix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_news_uix', 'users_news', type_='unique')
    op.drop_table('users_news')
    op.drop_index(op.f('ix_news_created_at'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
