name: Tests
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Check code with Python Black
        run: |
          pip install black==19.10b0
          black --check depc consumer scheduler

  tests:
    runs-on: ubuntu-18.04
    services:
      neo4j:
        image: neo4j:3.4.18
        env:
          NEO4J_AUTH: neo4j/foobar
          NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
          NEO4J_dbms_connector_http_advertised__address: localhost:7474
        ports:
          - 7687:7687
          - 7474:7474
    strategy:
      matrix:
          python-version: [3.6, 3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name : Install packages
        run: |
          sudo apt-get install libsnappy-dev
          pip install python-snappy==0.5.4
          pip install -r requirements.txt
      - name: Execute tests
        run: make tests
